# Generated by Django 4.0.5 on 2023-09-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_contenido_alter_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='contenido',
            field=models.TextField(max_length=1500),
        ),
    ]
