# Generated by Django 4.0.5 on 2023-11-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presbiterios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presbiterios',
            name='imagen',
            field=models.ImageField(upload_to='presbiterios'),
        ),
    ]
