# Generated by Django 4.0.5 on 2023-11-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presbiterios', '0002_alter_presbiterios_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presbiterios',
            new_name='PresbiteriosDef',
        ),
    ]
