# Generated by Django 4.0.5 on 2022-10-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_directiva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta_directiva',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
