# Generated by Django 4.0.5 on 2022-10-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_directiva', '0002_junta_directiva_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junta_directiva',
            name='imagen',
            field=models.ImageField(upload_to='junta_directiva'),
        ),
    ]
