# Generated by Django 4.0.5 on 2022-10-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_directiva', '0003_alter_junta_directiva_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junta_directiva',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
