# Generated by Django 4.0.5 on 2022-10-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_directiva', '0004_alter_junta_directiva_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junta_directiva',
            name='imagen',
            field=models.ImageField(null=True, upload_to='junta_directiva'),
        ),
    ]
