# Generated by Django 4.0.5 on 2022-11-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_directiva', '0006_alter_junta_directiva_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junta_directiva',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
