# Generated by Django 4.0.5 on 2023-11-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebDefensores', '0002_categoria_alter_noticiatres_contenido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auto',
            new_name='autor',
        ),
    ]
