# Generated by Django 4.0.5 on 2023-11-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebDefensores', '0003_rename_auto_post_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticiaUno',
            new_name='Noticias',
        ),
        migrations.DeleteModel(
            name='NoticiaDos',
        ),
        migrations.DeleteModel(
            name='NoticiaTres',
        ),
        migrations.AlterModelOptions(
            name='noticias',
            options={'verbose_name': 'Noticias', 'verbose_name_plural': 'Noticias'},
        ),
    ]
