# Generated by Django 4.2.10 on 2024-02-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebDefensores', '0004_rename_noticiauno_noticias_delete_noticiados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('contenido', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Contactano',
                'verbose_name_plural': 'Contactanos',
            },
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenidoPequeno',
            field=models.TextField(max_length=500),
        ),
    ]
