# Generated by Django 4.2.10 on 2024-02-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebDefensores', '0005_contactanos_alter_noticias_contenido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactanos',
            old_name='contenido',
            new_name='mensaje',
        ),
    ]
