# Generated by Django 4.2.10 on 2024-02-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebDefensores', '0006_rename_contenido_contactanos_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactanos',
            name='correo',
            field=models.EmailField(max_length=100, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='telefono',
            field=models.CharField(max_length=100, verbose_name='Teléfono'),
        ),
    ]
