# Generated by Django 4.2.10 on 2024-03-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebDefensores', '0008_useraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
