# Generated by Django 4.2.10 on 2024-03-23 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoWebDefensores', '0009_delete_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='mensaje',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.TextField(max_length=2500),
        ),
    ]
