# Generated by Django 4.2.10 on 2024-03-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebDefensores', '0010_noticias_autor_alter_contactanos_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.TextField(max_length=2500, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenidoPequeno',
            field=models.TextField(max_length=500, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='tituloGrande',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='tituloPequeno',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
    ]
