# Generated by Django 4.2.10 on 2024-04-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebDefensores', '0011_alter_noticias_contenido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('comentario', models.TextField(max_length=2500)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
