# Generated by Django 4.2.10 on 2024-04-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebDefensores', '0013_imagencarrusel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.TextField(max_length=2500, verbose_name='Contenido Grande'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='tituloGrande',
            field=models.CharField(max_length=250, verbose_name='Título Grande'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
