# Generated by Django 4.2.10 on 2024-03-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0005_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='contenido',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
