# Generated by Django 4.2.10 on 2024-03-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0009_alter_imagen_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='contenido',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
