# Generated by Django 4.2.10 on 2024-03-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0010_alter_imagen_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='contenido',
            field=models.TextField(default='', max_length=200),
        ),
    ]
