# Generated by Django 4.2.10 on 2024-04-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0012_alter_imagen_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotrosdef',
            name='contenido',
            field=models.TextField(max_length=5000),
        ),
    ]
