# Generated by Django 4.2.10 on 2024-04-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0013_alter_nosotrosdef_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField(max_length=200)),
                ('archivo', models.FileField(upload_to='archivos/')),
            ],
        ),
    ]
