# Generated by Django 4.0.5 on 2023-11-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamentos_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamentos',
            new_name='DepartamentosDef',
        ),
    ]
